// ignore_for_file: unused_import, unused_element
part of 'main.dart';

enum AuraLocale { en, ru, zh, de, fr, es, ar, fa, tr, pt, ja, ko, uk, it }

class S {
  static AuraLocale _locale = AuraLocale.en;
  static AuraLocale get locale => _locale;

  static Future<void> init() async {
    final p = await SharedPreferences.getInstance();
    final saved = p.getString('aura_locale');
    if (saved != null) {
      _locale = AuraLocale.values.firstWhere((e) => e.name == saved, orElse: () => AuraLocale.en);
    } else {
      final tag = ui.PlatformDispatcher.instance.locale.languageCode;
      _locale = AuraLocale.values.firstWhere((e) => e.name == tag, orElse: () => AuraLocale.en);
    }
  }

  static Future<void> setLocale(AuraLocale l) async {
    _locale = l;
    final p = await SharedPreferences.getInstance();
    await p.setString('aura_locale', l.name);
  }

  static String t(String key) =>
      _strings[_locale]?[key] ?? _strings[AuraLocale.en]![key] ?? key;

  static const Map<AuraLocale, Map<String, String>> _strings = {
    AuraLocale.en: {
      'app_name': 'AURA VPN', 'connected': 'CONNECTED', 'connecting': 'CONNECTING…',
      'disconnected': 'DISCONNECTED', 'error': 'ERROR', 'no_nodes': 'NO NODES',
      'add_via_qr': 'Add via QR, key or subscription', 'scan_qr': 'SCAN QR',
      'nodes': 'NODES', 'sort_by_ping': 'SORT BY PING', 'settings': 'SETTINGS',
      'qr_scanner': 'QR SCANNER', 'kill_switch': 'Kill Switch',
      'kill_switch_sub': 'Block traffic if VPN drops',
      'auto_rotate': 'Auto-Rotate', 'auto_rotate_sub': 'Switch node after {n} fails',
      'ai_bypass': 'AI Auto-Bypass', 'ai_bypass_sub': 'Automatic bypass without updates',
      'sync_rules': 'Sync Rules', 'sync_rules_sub': 'Update rules from server',
      'add_node': 'ADD NODE', 'add_key': 'ADD KEY', 'add_sub': 'ADD SUBSCRIPTION',
      'refresh_all': 'REFRESH ALL', 'subscriptions': 'SUBSCRIPTIONS',
      'protection': 'PROTECTION', 'logs': 'LOGS', 'clear': 'CLEAR',
      'cancel': 'Cancel', 'save': 'Save', 'done': 'Done', 'scan_again': 'Scan Again',
      'rename_group': 'Rename Group', 'rename_node': 'Rename Node',
      'sub_added': 'SUB ADDED', 'node_added': 'NODE ADDED', 'unknown_qr': 'UNKNOWN QR',
      'appearance': 'APPEARANCE', 'theme': 'Theme', 'theme_dark': 'Dark',
      'theme_light': 'Light', 'theme_system': 'System', 'language': 'Language',
      'ok': 'OK', 'download_log': 'Copy Log', 'kill_switch_on': 'Kill Switch ON',
      'proxy_chain': 'Proxy Chain', 'proxy_chain_on': 'PROXY CHAIN: ON',
      'proxy_chain_off': 'PROXY CHAIN: OFF', 'proxy_chain_desc': 'TUN → SOCKS5 → VPN',
      'ai_bar_prefix': '🤖  AI BYPASS: ',
      'profiles': 'PROFİLLER', 'profile_new': 'Yeni profil', 'profile_name': 'Profil adı',
      'profile_switch': 'Profil değiştir', 'profile_delete': 'Profili sil', 'profile_active': 'AKTİF',
      'backup': 'YEDEK', 'backup_export': 'Yedeği dışa aktar',
      'backup_import': 'Yedeği içe aktar', 'backup_password': 'Şifre (isteğe bağlı)',
      'backup_ok': 'Yedek oluşturuldu', 'backup_fail': 'Yedek başarısız',
      'restore_ok': 'Geri yükleme başarılı', 'restore_fail': 'Geri yükleme başarısız',
      'restore_confirm': 'Mevcut veriler değiştirilecek. Devam edilsin mi?',
      'backup_copied': 'Yedek panoya kopyalandı', 'backup_password_hint': 'Şifre (isteğe bağlı)',
      'split_tunnel': 'BÖLÜNMÜŞ TÜNEL', 'split_mode': 'Mod',
      'split_bypass': 'Bypass (seçili uygulamalar VPN\'yi atlar)',
      'split_proxy': 'Proxy (yalnızca seçili uygulamalar VPN üzerinden)',
      'split_disabled': 'Devre dışı (tüm trafik VPN üzerinden)',
      'split_apps': 'Uygulamalar', 'split_search': 'Uygulama ara…',
      'favourites': 'FAVORİLER', 'favourite_add': 'Favorilere ekle',
      'favourite_remove': 'Favorilerden kaldır',
      'search_nodes': 'Düğüm ara…', 'traffic_up': '↑', 'traffic_down': '↓',
      'session_time': 'Oturum', 'delete': 'Sil', 'rename': 'Yeniden adlandır',
    },
    AuraLocale.pt: {
      'app_name': 'AURA VPN', 'connected': 'CONECTADO', 'connecting': 'CONECTANDO…',
      'disconnected': 'DESCONECTADO', 'error': 'ERRO', 'no_nodes': 'SEM NÓS',
      'add_via_qr': 'Adicionar via QR, chave ou assinatura', 'scan_qr': 'ESCANEAR QR',
      'nodes': 'NÓS', 'sort_by_ping': 'POR PING', 'settings': 'CONFIGURAÇÕES',
      'qr_scanner': 'SCANNER QR', 'kill_switch': 'Kill Switch',
      'kill_switch_sub': 'Bloquear tráfego se a VPN cair',
      'auto_rotate': 'Rotação auto', 'auto_rotate_sub': 'Mudar após {n} falhas',
      'ai_bypass': 'IA Auto-bypass', 'ai_bypass_sub': 'Bypass automático sem atualizações',
      'sync_rules': 'Sync regras', 'sync_rules_sub': 'Atualizar do servidor',
      'add_node': 'ADICIONAR NÓ', 'add_key': 'ADICIONAR CHAVE',
      'add_sub': 'ADICIONAR ASSINATURA', 'refresh_all': 'ATUALIZAR TUDO',
      'subscriptions': 'ASSINATURAS', 'protection': 'PROTEÇÃO', 'logs': 'REGISTROS',
      'clear': 'LIMPAR', 'cancel': 'Cancelar', 'save': 'Salvar',
      'done': 'Feito', 'scan_again': 'Escanear novamente',
      'rename_group': 'Renomear grupo', 'rename_node': 'Renomear nó',
      'sub_added': 'ASSINATURA ADICIONADA', 'node_added': 'NÓ ADICIONADO',
      'unknown_qr': 'QR DESCONHECIDO',
      'appearance': 'APARÊNCIA', 'theme': 'Tema', 'theme_dark': 'Escuro',
      'theme_light': 'Claro', 'theme_system': 'Sistema', 'language': 'Idioma',
      'ok': 'OK', 'download_log': 'Copiar registro', 'kill_switch_on': 'Kill Switch ATIVO',
      'ai_bar_prefix': '🤖  BYPASS IA: ',
      'profiles': 'PERFIS', 'profile_new': 'Novo perfil', 'profile_name': 'Nome do perfil',
      'profile_switch': 'Trocar perfil', 'profile_delete': 'Excluir perfil', 'profile_active': 'ATIVO',
      'backup': 'BACKUP', 'backup_export': 'Exportar backup',
      'backup_import': 'Importar backup', 'backup_password': 'Senha (opcional)',
      'backup_ok': 'Backup criado', 'backup_fail': 'Falha no backup',
      'restore_ok': 'Restaurado com sucesso', 'restore_fail': 'Falha na restauração',
      'restore_confirm': 'Os dados atuais serão substituídos. Continuar?',
      'backup_copied': 'Backup copiado para a área de transferência',
      'backup_password_hint': 'Senha (opcional)',
      'split_tunnel': 'SPLIT TUNNEL', 'split_mode': 'Modo',
      'split_bypass': 'Bypass (apps selecionados ignoram VPN)',
      'split_proxy': 'Proxy (apenas apps selecionados via VPN)',
      'split_disabled': 'Desativado (todo tráfego via VPN)',
      'split_apps': 'Aplicativos', 'split_search': 'Buscar apps…',
      'favourites': 'FAVORITOS', 'favourite_add': 'Adicionar aos favoritos',
      'favourite_remove': 'Remover dos favoritos',
      'search_nodes': 'Pesquisar nós…', 'traffic_up': '↑', 'traffic_down': '↓',
      'session_time': 'Sessão', 'delete': 'Excluir', 'rename': 'Renomear',
    },
    AuraLocale.ja: {
      'app_name': 'AURA VPN', 'connected': '接続済み', 'connecting': '接続中…',
      'disconnected': '切断', 'error': 'エラー', 'no_nodes': 'ノードなし',
      'add_via_qr': 'QR・キー・サブスクで追加', 'scan_qr': 'QRスキャン',
      'nodes': 'ノード', 'sort_by_ping': 'Pingで並べる', 'settings': '設定',
      'qr_scanner': 'QRスキャナー', 'kill_switch': 'キルスイッチ',
      'kill_switch_sub': 'VPN切断時にトラフィックをブロック',
      'auto_rotate': '自動ローテーション', 'auto_rotate_sub': '{n}回失敗後に切替',
      'ai_bypass': 'AIバイパス', 'ai_bypass_sub': '自動バイパス（更新不要）',
      'sync_rules': 'ルール同期', 'sync_rules_sub': 'サーバーから更新',
      'add_node': 'ノード追加', 'add_key': 'キー追加',
      'add_sub': 'サブスク追加', 'refresh_all': '全て更新',
      'subscriptions': 'サブスクリプション', 'protection': '保護', 'logs': 'ログ',
      'clear': 'クリア', 'cancel': 'キャンセル', 'save': '保存',
      'done': '完了', 'scan_again': '再スキャン',
      'rename_group': 'グループ名を変更', 'rename_node': 'ノード名を変更',
      'sub_added': 'サブスク追加済み', 'node_added': 'ノード追加済み',
      'unknown_qr': '不明なQR',
      'appearance': '外観', 'theme': 'テーマ', 'theme_dark': 'ダーク',
      'theme_light': 'ライト', 'theme_system': 'システム', 'language': '言語',
      'ok': 'OK', 'download_log': 'ログをコピー', 'kill_switch_on': 'キルスイッチON',
      'ai_bar_prefix': '🤖  AIバイパス: ',
      'profiles': 'プロファイル', 'profile_new': '新しいプロファイル',
      'profile_name': 'プロファイル名', 'profile_switch': 'プロファイル切替',
      'profile_delete': 'プロファイル削除', 'profile_active': 'アクティブ',
      'backup': 'バックアップ', 'backup_export': 'バックアップを書き出す',
      'backup_import': 'バックアップを読み込む', 'backup_password': 'パスワード（任意）',
      'backup_ok': 'バックアップ作成済み', 'backup_fail': 'バックアップ失敗',
      'restore_ok': '復元成功', 'restore_fail': '復元失敗',
      'restore_confirm': '現在のデータが置き換えられます。続けますか？',
      'backup_copied': 'バックアップをクリップボードにコピーしました',
      'backup_password_hint': 'パスワード（任意）',
      'split_tunnel': 'スプリットトンネル', 'split_mode': 'モード',
      'split_bypass': 'バイパス（選択したアプリはVPNをスキップ）',
      'split_proxy': 'プロキシ（選択したアプリのみVPN経由）',
      'split_disabled': '無効（すべてのトラフィックがVPN経由）',
      'split_apps': 'アプリケーション', 'split_search': 'アプリを検索…',
      'favourites': 'お気に入り', 'favourite_add': 'お気に入りに追加',
      'favourite_remove': 'お気に入りから削除',
      'search_nodes': 'ノードを検索…', 'traffic_up': '↑', 'traffic_down': '↓',
      'session_time': 'セッション', 'delete': '削除', 'rename': '名前を変更',
    },
    AuraLocale.ko: {
      'app_name': 'AURA VPN', 'connected': '연결됨', 'connecting': '연결 중…',
      'disconnected': '연결 끊김', 'error': '오류', 'no_nodes': '노드 없음',
      'add_via_qr': 'QR코드, 키 또는 구독으로 추가', 'scan_qr': 'QR 스캔',
      'nodes': '노드', 'sort_by_ping': '핑순 정렬', 'settings': '설정',
      'qr_scanner': 'QR 스캐너', 'kill_switch': '킬 스위치',
      'kill_switch_sub': 'VPN 끊길 시 트래픽 차단',
      'auto_rotate': '자동 교체', 'auto_rotate_sub': '{n}회 실패 후 전환',
      'ai_bypass': 'AI 자동 우회', 'ai_bypass_sub': '업데이트 없이 자동 우회',
      'sync_rules': '규칙 동기화', 'sync_rules_sub': '서버에서 업데이트',
      'add_node': '노드 추가', 'add_key': '키 추가',
      'add_sub': '구독 추가', 'refresh_all': '전체 새로고침',
      'subscriptions': '구독', 'protection': '보호', 'logs': '로그',
      'clear': '지우기', 'cancel': '취소', 'save': '저장',
      'done': '완료', 'scan_again': '다시 스캔',
      'rename_group': '그룹 이름 변경', 'rename_node': '노드 이름 변경',
      'sub_added': '구독 추가됨', 'node_added': '노드 추가됨',
      'unknown_qr': '알 수 없는 QR',
      'appearance': '외관', 'theme': '테마', 'theme_dark': '다크',
      'theme_light': '라이트', 'theme_system': '시스템', 'language': '언어',
      'ok': '확인', 'download_log': '로그 복사', 'kill_switch_on': '킬 스위치 ON',
      'ai_bar_prefix': '🤖  AI 우회: ',
      'profiles': '프로필', 'profile_new': '새 프로필', 'profile_name': '프로필 이름',
      'profile_switch': '프로필 전환', 'profile_delete': '프로필 삭제', 'profile_active': '활성',
      'backup': '백업', 'backup_export': '백업 내보내기',
      'backup_import': '백업 가져오기', 'backup_password': '비밀번호 (선택)',
      'backup_ok': '백업 생성됨', 'backup_fail': '백업 실패',
      'restore_ok': '복원 성공', 'restore_fail': '복원 실패',
      'restore_confirm': '현재 데이터가 교체됩니다. 계속하시겠습니까?',
      'backup_copied': '백업이 클립보드에 복사되었습니다',
      'backup_password_hint': '비밀번호 (선택)',
      'split_tunnel': '분할 터널', 'split_mode': '모드',
      'split_bypass': '바이패스 (선택한 앱이 VPN을 우회)',
      'split_proxy': '프록시 (선택한 앱만 VPN 통과)',
      'split_disabled': '비활성 (모든 트래픽이 VPN 통과)',
      'split_apps': '앱', 'split_search': '앱 검색…',
      'favourites': '즐겨찾기', 'favourite_add': '즐겨찾기에 추가',
      'favourite_remove': '즐겨찾기에서 제거',
      'search_nodes': '노드 검색…', 'traffic_up': '↑', 'traffic_down': '↓',
      'session_time': '세션', 'delete': '삭제', 'rename': '이름 변경',
    },
    AuraLocale.uk: {
      'app_name': 'AURA VPN', 'connected': 'ПІДКЛЮЧЕНО', 'connecting': 'ПІДКЛЮЧЕННЯ…',
      'disconnected': 'ВІДКЛЮЧЕНО', 'error': 'ПОМИЛКА', 'no_nodes': 'НЕМАЄ ВУЗЛІВ',
      'add_via_qr': 'Додати через QR, ключ або підписку', 'scan_qr': 'СКАНУВАТИ QR',
      'nodes': 'ВУЗЛІВ', 'sort_by_ping': 'ЗА ПІНГОМ', 'settings': 'НАЛАШТУВАННЯ',
      'qr_scanner': 'QR СКАНЕР', 'kill_switch': 'Kill Switch',
      'kill_switch_sub': 'Блокувати трафік при розриві VPN',
      'auto_rotate': 'Авто-ротація', 'auto_rotate_sub': 'Змінити після {n} невдач',
      'ai_bypass': 'AI Авто-обхід', 'ai_bypass_sub': 'Автоматичний обхід без оновлень',
      'sync_rules': 'Синхронізація', 'sync_rules_sub': 'Оновити правила з сервера',
      'add_node': 'ДОДАТИ ВУЗОЛ', 'add_key': 'ДОДАТИ КЛЮЧ',
      'add_sub': 'ДОДАТИ ПІДПИСКУ', 'refresh_all': 'ОНОВИТИ ВСЕ',
      'subscriptions': 'ПІДПИСКИ', 'protection': 'ЗАХИСТ', 'logs': 'ЛОГИ',
      'clear': 'ОЧИСТИТИ', 'cancel': 'Скасувати', 'save': 'Зберегти',
      'done': 'Готово', 'scan_again': 'Сканувати знову',
      'rename_group': 'Перейменувати групу', 'rename_node': 'Перейменувати вузол',
      'sub_added': 'ПІДПИСКУ ДОДАНО', 'node_added': 'ВУЗОЛ ДОДАНО',
      'unknown_qr': 'НЕВІДОМИЙ QR',
      'appearance': 'ЗОВНІШНІЙ ВИГЛЯД', 'theme': 'Тема', 'theme_dark': 'Темна',
      'theme_light': 'Світла', 'theme_system': 'Системна', 'language': 'Мова',
      'ok': 'ОК', 'download_log': 'Скопіювати лог', 'kill_switch_on': 'Kill Switch УВІМКНЕНО',
      'ai_bar_prefix': '🤖  AI ОБХІД: ',
      'profiles': 'ПРОФІЛІ', 'profile_new': 'Новий профіль', 'profile_name': 'Назва профілю',
      'profile_switch': 'Переключити', 'profile_delete': 'Видалити профіль', 'profile_active': 'АКТИВНИЙ',
      'backup': 'РЕЗЕРВНА КОПІЯ', 'backup_export': 'Створити резервну копію',
      'backup_import': 'Відновити з копії', 'backup_password': 'Пароль (необов\'язково)',
      'backup_ok': 'Копію створено', 'backup_fail': 'Помилка створення копії',
      'restore_ok': 'Відновлено успішно', 'restore_fail': 'Помилка відновлення',
      'restore_confirm': 'Поточні дані будуть замінені. Продовжити?',
      'backup_copied': 'Резервну копію скопійовано в буфер',
      'backup_password_hint': 'Пароль (необов\'язково)',
      'split_tunnel': 'РОЗДІЛЬНИЙ ТУНЕЛЬ', 'split_mode': 'Режим',
      'split_bypass': 'Байпас (обрані застосунки оминають VPN)',
      'split_proxy': 'Проксі (тільки обрані застосунки через VPN)',
      'split_disabled': 'Вимкнено (весь трафік через VPN)',
      'split_apps': 'Застосунки', 'split_search': 'Пошук застосунків…',
      'favourites': 'ОБРАНЕ', 'favourite_add': 'Додати до обраного',
      'favourite_remove': 'Видалити з обраного',
      'search_nodes': 'Пошук вузлів…', 'traffic_up': '↑', 'traffic_down': '↓',
      'session_time': 'Сесія', 'delete': 'Видалити', 'rename': 'Перейменувати',
    },
    AuraLocale.it: {
      'app_name': 'AURA VPN', 'connected': 'CONNESSO', 'connecting': 'CONNESSIONE…',
      'disconnected': 'DISCONNESSO', 'error': 'ERRORE', 'no_nodes': 'NESSUN NODO',
      'add_via_qr': 'Aggiungi tramite QR, chiave o abbonamento', 'scan_qr': 'SCANSIONA QR',
      'nodes': 'NODI', 'sort_by_ping': 'PER PING', 'settings': 'IMPOSTAZIONI',
      'qr_scanner': 'SCANNER QR', 'kill_switch': 'Kill Switch',
      'kill_switch_sub': 'Blocca il traffico se la VPN cade',
      'auto_rotate': 'Rotazione auto', 'auto_rotate_sub': 'Cambia dopo {n} fallimenti',
      'ai_bypass': 'AI Auto-bypass', 'ai_bypass_sub': 'Bypass automatico senza aggiornamenti',
      'sync_rules': 'Sync regole', 'sync_rules_sub': 'Aggiorna dal server',
      'add_node': 'AGGIUNGI NODO', 'add_key': 'AGGIUNGI CHIAVE',
      'add_sub': 'AGGIUNGI ABBONAMENTO', 'refresh_all': 'AGGIORNA TUTTO',
      'subscriptions': 'ABBONAMENTI', 'protection': 'PROTEZIONE', 'logs': 'REGISTRI',
      'clear': 'CANCELLA', 'cancel': 'Annulla', 'save': 'Salva',
      'done': 'Fatto', 'scan_again': 'Scansiona di nuovo',
      'rename_group': 'Rinomina gruppo', 'rename_node': 'Rinomina nodo',
      'sub_added': 'ABBONAMENTO AGGIUNTO', 'node_added': 'NODO AGGIUNTO',
      'unknown_qr': 'QR SCONOSCIUTO',
      'appearance': 'ASPETTO', 'theme': 'Tema', 'theme_dark': 'Scuro',
      'theme_light': 'Chiaro', 'theme_system': 'Sistema', 'language': 'Lingua',
      'ok': 'OK', 'download_log': 'Copia registro', 'kill_switch_on': 'Kill Switch ATTIVO',
      'ai_bar_prefix': '🤖  BYPASS IA: ',
      'profiles': 'PROFILI', 'profile_new': 'Nuovo profilo', 'profile_name': 'Nome profilo',
      'profile_switch': 'Cambia profilo', 'profile_delete': 'Elimina profilo', 'profile_active': 'ATTIVO',
      'backup': 'BACKUP', 'backup_export': 'Esporta backup',
      'backup_import': 'Importa backup', 'backup_password': 'Password (opzionale)',
      'backup_ok': 'Backup creato', 'backup_fail': 'Backup fallito',
      'restore_ok': 'Ripristinato con successo', 'restore_fail': 'Ripristino fallito',
      'restore_confirm': 'I dati attuali verranno sostituiti. Continuare?',
      'backup_copied': 'Backup copiato negli appunti', 'backup_password_hint': 'Password (opzionale)',
      'split_tunnel': 'SPLIT TUNNEL', 'split_mode': 'Modalità',
      'split_bypass': 'Bypass (le app selezionate bypassano la VPN)',
      'split_proxy': 'Proxy (solo le app selezionate tramite VPN)',
      'split_disabled': 'Disabilitato (tutto il traffico tramite VPN)',
      'split_apps': 'Applicazioni', 'split_search': 'Cerca app…',
      'favourites': 'PREFERITI', 'favourite_add': 'Aggiungi ai preferiti',
      'favourite_remove': 'Rimuovi dai preferiti',
      'search_nodes': 'Cerca nodi…', 'traffic_up': '↑', 'traffic_down': '↓',
      'session_time': 'Sessione', 'delete': 'Elimina', 'rename': 'Rinomina',
    },
  };

  static const Map<AuraLocale, String> localeNames = {
    AuraLocale.en: 'English', AuraLocale.ru: 'Русский', AuraLocale.zh: '中文',
    AuraLocale.de: 'Deutsch', AuraLocale.fr: 'Français', AuraLocale.es: 'Español',
    AuraLocale.ar: 'العربية', AuraLocale.fa: 'فارسی', AuraLocale.tr: 'Türkçe',
    AuraLocale.pt: 'Português', AuraLocale.ja: '日本語', AuraLocale.ko: '한국어',
    AuraLocale.uk: 'Українська', AuraLocale.it: 'Italiano',
  };
}
