// ignore_for_file: unused_import, unused_element, prefer_const_constructors, prefer_const_literals_to_create_immutables, deprecated_member_use, prefer_final_fields, unnecessary_to_list_in_spreads, unused_local_variable, dead_code, unnecessary_null_comparison, avoid_print, unused_field, unnecessary_statements, duplicate_ignore, unnecessary_brace_in_string_interp, prefer_interpolation_to_compose_strings, unnecessary_string_interpolations, unnecessary_string_escapes, library_private_types_in_public_api, non_constant_identifier_names, constant_identifier_names, use_build_context_synchronously, no_leading_underscores_for_local_identifiers, unnecessary_import, depend_on_referenced_packages, unnecessary_overrides, avoid_unnecessary_containers, sized_box_for_whitespace, sort_child_properties_last, prefer_final_locals, omit_local_variable_types, always_use_package_imports
part of 'main.dart';

enum AuraLocale { en, ru, zh, de, fr, es, ar, fa, tr, pt, ja, ko, uk, it }

class S {
  static AuraLocale _locale = AuraLocale.en;
  static AuraLocale get locale => _locale;

  static Future<void> init() async {
    final p = await SharedPreferences.getInstance();
    final saved = p.getString('aura_locale');
    if (saved != null) {
      _locale = AuraLocale.values.firstWhere((e) => e.name == saved, orElse: () => AuraLocale.en);
    } else {
      final tag = ui.PlatformDispatcher.instance.locale.languageCode;
      _locale = AuraLocale.values.firstWhere((e) => e.name == tag, orElse: () => AuraLocale.en);
    }
  }

  static Future<void> setLocale(AuraLocale l) async {
    _locale = l;
    final p = await SharedPreferences.getInstance();
    await p.setString('aura_locale', l.name);
  }

  static String t(String key) =>
      _strings[_locale]?[key] ?? _strings[AuraLocale.en]![key] ?? key;

  static const Map<AuraLocale, Map<String, String>> _strings = {
    AuraLocale.en: {
      'app_name': 'VLY', 'connected': 'CONNECTED', 'connecting': 'CONNECTING…',
      'disconnected': 'DISCONNECTED', 'error': 'ERROR', 'no_nodes': 'NO NODES',
      'add_via_qr': 'Add via QR, key or subscription', 'scan_qr': 'SCAN QR',
      'nodes': 'NODES', 'sort_by_ping': 'SORT BY PING', 'settings': 'SETTINGS',
      'qr_scanner': 'QR SCANNER', 'kill_switch': 'Kill Switch',
      'kill_switch_sub': 'Block traffic if VPN drops',
      'auto_rotate': 'Auto-Rotate', 'auto_rotate_sub': 'Switch node after {n} fails',
      'ai_bypass': 'AI Auto-Bypass', 'ai_bypass_sub': 'Automatic bypass without updates',
      'sync_rules': 'Sync Rules', 'sync_rules_sub': 'Update rules from server',
      'add_node': 'ADD NODE', 'add_key': 'ADD KEY', 'add_sub': 'ADD SUBSCRIPTION',
      'refresh_all': 'REFRESH ALL', 'subscriptions': 'SUBSCRIPTIONS',
      'protection': 'PROTECTION', 'logs': 'LOGS', 'clear': 'CLEAR',
      'cancel': 'Cancel', 'save': 'Save', 'done': 'Done', 'scan_again': 'Scan Again',
      'rename_group': 'Rename Group', 'rename_node': 'Rename Node',
      'sub_added': 'SUB ADDED', 'node_added': 'NODE ADDED', 'unknown_qr': 'UNKNOWN QR',
      'appearance': 'APPEARANCE', 'theme': 'Theme', 'theme_dark': 'Dark',
      'theme_light': 'Light', 'theme_system': 'System', 'language': 'Language',
      'ok': 'OK', 'download_log': 'Copy Log', 'kill_switch_on': 'Kill Switch ON',
      'ai_bar_prefix': '🤖  AI BYPASS: ',
      // v3.0
      'profiles': 'PROFILES', 'profile_new': 'New Profile', 'profile_name': 'Profile name',
      'profile_switch': 'Switch Profile', 'profile_delete': 'Delete Profile',
      'profile_active': 'ACTIVE',
      'backup': 'BACKUP & RESTORE', 'backup_export': 'Export Backup',
      'backup_import': 'Import Backup', 'backup_password': 'Backup password (optional)',
      'backup_ok': 'Backup created', 'backup_fail': 'Backup failed',
      'restore_ok': 'Restored successfully', 'restore_fail': 'Restore failed',
      'restore_confirm': 'This will replace current data. Continue?',
      'split_tunnel': 'SPLIT TUNNEL', 'split_mode': 'Mode',
      'split_bypass': 'Bypass (selected apps skip VPN)',
      'split_proxy': 'Proxy (only selected apps use VPN)',
      'split_disabled': 'Disabled (all traffic via VPN)',
      'split_apps': 'Applications', 'split_search': 'Search apps…',
      'favourites': 'FAVOURITES', 'favourite_add': 'Add to Favourites',
      'favourite_remove': 'Remove from Favourites',
      'search_nodes': 'Search nodes…',
      'traffic_up': '↑', 'traffic_down': '↓',
      'session_time': 'Session',
      'delete': 'Delete', 'rename': 'Rename',
      'backup_copied': 'Backup copied to clipboard',
      'backup_password_hint': 'Password (optional)',
      // v5.9 new keys
      'section_tunnel': 'TUNNEL', 'section_security': 'SECURITY & BYPASS',
      'section_subscriptions': 'SUBSCRIPTIONS', 'section_connection': 'CONNECTION',
      'section_interface': 'INTERFACE', 'section_data': 'DATA',
      'tunnel_settings': 'Tunnel Settings', 'mux_enable': 'Enable MUX',
      'mux_sub': 'TCP stream multiplexing', 'tun_enable': 'Enable TUN',
      'tun_sub': 'Intercepts all OS traffic', 'ip_preference': 'IP Preference',
      'dns_enable': 'DNS for TUN', 'dns_sub': 'Use DoH inside tunnel',
      'lan_share': 'LAN Sharing', 'lan_sub': 'Share proxy with local network',
      'packet_sniff': 'Packet Sniffing', 'packet_sniff_sub': 'DPI traffic classification',
      'system_proxy': 'System Proxy', 'system_proxy_sub': 'Set system HTTP proxy too',
      'node_rename': 'Rename', 'node_share': 'Share node',
      'node_reset': 'Reset to original key',
      'node_reset_confirm_title': 'Reset config?',
      'node_reset_confirm_body': 'Key returns to provider original. AI patches removed.',
      'node_modified': '⚠️ Key modified by AI/camouflage',
      'camouflage': 'Traffic Camouflage', 'camouflage_sub': 'Disguise VPN as a service',
      'camo_none': 'No camouflage', 'camo_browser': 'HTTPS Browser',
      'camo_telegram': 'Telegram CDN', 'camo_netflix': 'Netflix Stream',
      'camo_youtube': 'YouTube Video', 'camo_discord': 'Discord Gateway',
      'camo_cloudflare': 'Cloudflare WARP', 'camo_microsoft': 'Windows Update',
      'camo_apple': 'iCloud Sync', 'camo_naive': 'NaïveProxy H2',
      'ping_settings': 'Ping Settings', 'ping_type': 'Ping Type',
      'ping_url_label': 'Test URL', 'sub_settings': 'Update Settings',
      'sub_auto_update': 'Auto Update', 'sub_interval': 'Interval (hours)',
      'sub_on_open': 'Update on launch', 'sub_ping_open': 'Ping on launch',
      'sub_connect_open': 'Connect on launch', 'sub_sort_label': 'Sort order',
      'sub_sort_none': 'No sort', 'sub_sort_ping': 'By ping',
      'sub_sort_alpha': 'Alphabetical', 'sub_user_agent': 'User Agent',
      'sub_allow_dups': 'Allow duplicates',
      'theme_editor': 'My Theme', 'theme_preview': 'PREVIEW',
      'theme_colors': 'COLORS', 'theme_background': 'BACKGROUND',
      'theme_presets': 'QUICK PRESETS', 'theme_apply': 'APPLY THEME',
      'theme_pick_media': 'Photo / GIF / Video', 'theme_enter_path': 'Enter path',
      'theme_saved': 'Theme saved ✓',
      'reset': 'Reset', 'apply': 'Apply', 'confirm': 'Confirm',
      'loading': 'Loading…', 'success': 'Done', 'about_version': 'Version',
      'servers_title': 'Servers', 'ip_check_title': 'IP Check',
      'disconnect': 'Disconnect', 'reconnect': 'Reconnect',
      'select': 'Select', 'close': 'Close',
      'auto_connect': 'Auto-Connect', 'stealth_engine': 'Stealth Engine 3.0',
      'ai_bypass_engine': 'AI Bypass Engine', 'bypass_whitelist': 'Bypass Whitelists',
      'about_app': 'About', 'history': 'Connection History',
      'ping_via_proxy': 'via Proxy', 'ping_tcp': 'TCP', 'ping_icmp': 'ICMP',
      'lan_page': 'Local Network (LAN)', 'routing': 'ROUTING',
      'smart_routing': 'Smart Routing',
      'smart_routing_sub': 'RU domains direct, blocked via VPN',
      'ip_auto': 'Auto', 'ip_v4': 'IPv4 only', 'ip_v6': 'IPv6 only',
      'tun_mixed': 'Mixed', 'tun_mixed_sub': 'TCP + UDP via tun2socks',
      'tun_fakedns': 'FakeDNS', 'tun_fakedns_sub': 'DNS intercept — reduces leaks',
      'dns_address': 'DNS Address',
    },
    AuraLocale.ru: {
      'app_name': 'VLY', 'connected': 'ПОДКЛЮЧЕНО', 'connecting': 'ПОДКЛЮЧЕНИЕ…',
      'disconnected': 'ОТКЛЮЧЕНО', 'error': 'ОШИБКА', 'no_nodes': 'НЕТ УЗЛОВ',
      'add_via_qr': 'Добавьте через QR, ключ или подписку', 'scan_qr': 'СКАНИРОВАТЬ QR',
      'nodes': 'УЗЛОВ', 'sort_by_ping': 'ПО ПИНГУ', 'settings': 'НАСТРОЙКИ',
      'qr_scanner': 'QR СКАНЕР', 'kill_switch': 'Kill Switch',
      'kill_switch_sub': 'Блокировать трафик при разрыве VPN',
      'auto_rotate': 'Авто-ротация', 'auto_rotate_sub': 'Сменить после {n} неудач',
      'ai_bypass': 'AI Авто-обход', 'ai_bypass_sub': 'Автоматический обход без обновлений',
      'sync_rules': 'Синхронизация', 'sync_rules_sub': 'Обновить правила с сервера',
      'add_node': 'ДОБАВИТЬ УЗЕЛ', 'add_key': 'ДОБАВИТЬ КЛЮЧ',
      'add_sub': 'ДОБАВИТЬ ПОДПИСКУ', 'refresh_all': 'ОБНОВИТЬ ВСЁ',
      'subscriptions': 'ПОДПИСКИ', 'protection': 'ЗАЩИТА', 'logs': 'ЛОГИ',
      'clear': 'ОЧИСТИТЬ', 'cancel': 'Отмена', 'save': 'Сохранить',
      'done': 'Готово', 'scan_again': 'Сканировать снова',
      'rename_group': 'Переименовать группу', 'rename_node': 'Переименовать узел',
      'sub_added': 'ПОДПИСКА ДОБАВЛЕНА', 'node_added': 'УЗЕЛ ДОБАВЛЕН',
      'unknown_qr': 'НЕИЗВЕСТНЫЙ QR', 'appearance': 'ВНЕШНИЙ ВИД',
      'theme': 'Тема', 'theme_dark': 'Тёмная', 'theme_light': 'Светлая',
      'theme_system': 'Системная', 'language': 'Язык', 'ok': 'ОК',
      'download_log': 'Скопировать лог', 'kill_switch_on': 'Kill Switch ВКЛЮЧЁН',
      'backup_copied': 'Бэкап скопирован в буфер обмена',
      'backup_password_hint': 'Пароль (необязательно)',
      'ai_bar_prefix': '🤖  AI ОБХОД: ',
      'profiles': 'ПРОФИЛИ', 'profile_new': 'Новый профиль',
      'profile_name': 'Название профиля', 'profile_switch': 'Переключить',
      'profile_delete': 'Удалить профиль', 'profile_active': 'АКТИВЕН',
      'backup': 'РЕЗЕРВНАЯ КОПИЯ', 'backup_export': 'Создать резервную копию',
      'backup_import': 'Восстановить из копии',
      'backup_password': 'Пароль для копии (необязательно)',
      'backup_ok': 'Копия создана', 'backup_fail': 'Ошибка создания копии',
      'restore_ok': 'Восстановлено', 'restore_fail': 'Ошибка восстановления',
      'restore_confirm': 'Текущие данные будут заменены. Продолжить?',
      'split_tunnel': 'РАЗДЕЛЬНЫЙ ТУННЕЛЬ', 'split_mode': 'Режим',
      'split_bypass': 'Байпас (выбранные приложения минуют VPN)',
      'split_proxy': 'Прокси (только выбранные приложения через VPN)',
      'split_disabled': 'Отключён (весь трафик через VPN)',
      'split_apps': 'Приложения', 'split_search': 'Поиск приложений…',
      'favourites': 'ИЗБРАННОЕ', 'favourite_add': 'Добавить в избранное',
      'favourite_remove': 'Убрать из избранного',
      'search_nodes': 'Поиск узлов…',
      'traffic_up': '↑', 'traffic_down': '↓', 'session_time': 'Сессия',
      'delete': 'Удалить', 'rename': 'Переименовать',
      // v5.9 новые ключи
      'section_tunnel': 'ТУННЕЛЬ', 'section_security': 'БЕЗОПАСНОСТЬ И ОБХОД',
      'section_subscriptions': 'ПОДПИСКИ', 'section_connection': 'СОЕДИНЕНИЕ',
      'section_interface': 'ИНТЕРФЕЙС', 'section_data': 'ДАННЫЕ',
      'tunnel_settings': 'Настройки туннеля', 'mux_enable': 'Включить MUX',
      'mux_sub': 'Уплотнение TCP-потоков', 'tun_enable': 'Включить TUN',
      'tun_sub': 'Перехватывает весь трафик ОС', 'ip_preference': 'Предпочитаемый IP',
      'dns_enable': 'DNS для TUN', 'dns_sub': 'Использовать DoH внутри туннеля',
      'lan_share': 'Раздача в LAN', 'lan_sub': 'Прокси для устройств в сети',
      'packet_sniff': 'Анализ пакетов', 'packet_sniff_sub': 'DPI-детектирование трафика',
      'system_proxy': 'Системный прокси', 'system_proxy_sub': 'Устанавливать HTTP прокси в системе',
      'node_rename': 'Переименовать', 'node_share': 'Поделиться нодой',
      'node_reset': 'Сбросить к оригинальному ключу',
      'node_reset_confirm_title': 'Сбросить конфиг?',
      'node_reset_confirm_body': 'Ключ вернётся к оригинальному от провайдера. AI-патчи будут убраны.',
      'node_modified': '⚠️ Ключ изменён AI/маскировкой',
      'camouflage': 'Маскировка трафика', 'camouflage_sub': 'Замаскировать VPN под сервис',
      'camo_none': 'Без маскировки', 'camo_browser': 'HTTPS браузер',
      'camo_telegram': 'Telegram CDN', 'camo_netflix': 'Netflix Stream',
      'camo_youtube': 'YouTube Video', 'camo_discord': 'Discord Gateway',
      'camo_cloudflare': 'Cloudflare WARP', 'camo_microsoft': 'Windows Update',
      'camo_apple': 'iCloud Sync', 'camo_naive': 'NaïveProxy H2',
      'ping_settings': 'Настройки пинга', 'ping_type': 'Тип пинга',
      'ping_url_label': 'Тестовый URL', 'sub_settings': 'Параметры обновления',
      'sub_auto_update': 'Автообновление', 'sub_interval': 'Интервал (часы)',
      'sub_on_open': 'Обновлять при открытии', 'sub_ping_open': 'Пинговать при открытии',
      'sub_connect_open': 'Подключаться при открытии', 'sub_sort_label': 'Сортировка',
      'sub_sort_none': 'Без сортировки', 'sub_sort_ping': 'По пингу',
      'sub_sort_alpha': 'По алфавиту', 'sub_user_agent': 'User Agent',
      'sub_allow_dups': 'Разрешить дубликаты',
      'theme_editor': 'Моя тема', 'theme_preview': 'ПРЕВЬЮ',
      'theme_colors': 'ЦВЕТА', 'theme_background': 'ФОН',
      'theme_presets': 'БЫСТРЫЕ ПРЕСЕТЫ', 'theme_apply': 'ПРИМЕНИТЬ ТЕМУ',
      'theme_pick_media': 'Фото / GIF / Видео', 'theme_enter_path': 'Ввести путь',
      'theme_saved': 'Тема сохранена ✓',
      'reset': 'Сбросить', 'apply': 'Применить', 'confirm': 'Подтвердить',
      'loading': 'Загрузка…', 'success': 'Готово', 'about_version': 'Версия',
      'servers_title': 'Серверы', 'ip_check_title': 'Проверка IP',
      'disconnect': 'Отключить', 'reconnect': 'Переподключить',
      'select': 'Выбрать', 'close': 'Закрыть',
      'auto_connect': 'Автоподключение', 'stealth_engine': 'Stealth Engine 3.0',
      'ai_bypass_engine': 'AI Bypass Engine', 'bypass_whitelist': 'Обход белых списков',
      'about_app': 'О приложении', 'history': 'История подключений',
      'ping_via_proxy': 'через Proxy', 'ping_tcp': 'TCP', 'ping_icmp': 'ICMP',
      'lan_page': 'Локальная сеть (LAN)', 'routing': 'МАРШРУТИЗАЦИЯ',
      'smart_routing': 'Умная маршрутизация',
      'smart_routing_sub': 'RU-домены напрямую, заблокированные через VPN',
      'ip_auto': 'Авто', 'ip_v4': 'Только IPv4', 'ip_v6': 'Только IPv6',
      'tun_mixed': 'Смешанный', 'tun_mixed_sub': 'TCP + UDP через tun2socks',
      'tun_fakedns': 'FakeDNS', 'tun_fakedns_sub': 'DNS перехват — снижает утечки',
      'dns_address': 'DNS адрес',
    },
    // остальные языки — ключи из en (fallback автоматический)
    AuraLocale.zh: {
      'app_name': 'VLY', 'connected': '已连接', 'connecting': '连接中…',
      'disconnected': '已断开', 'error': '错误', 'no_nodes': '无节点',
      'add_via_qr': '通过二维码、密钥或订阅添加', 'scan_qr': '扫描二维码',
      'nodes': '节点', 'sort_by_ping': '按延迟排序', 'settings': '设置',
      'qr_scanner': '二维码扫描', 'kill_switch': 'Kill Switch',
      'kill_switch_sub': 'VPN断开时阻止流量',
      'auto_rotate': '自动轮换', 'auto_rotate_sub': '{n}次失败后切换节点',
      'ai_bypass': 'AI自动绕过', 'ai_bypass_sub': '无需更新自动绕过封锁',
      'sync_rules': '同步规则', 'sync_rules_sub': '从服务器更新规则',
      'add_node': '添加节点', 'add_key': '添加密钥', 'add_sub': '添加订阅',
      'refresh_all': '全部刷新', 'subscriptions': '订阅', 'protection': '保护',
      'logs': '日志', 'clear': '清除', 'cancel': '取消', 'save': '保存',
      'done': '完成', 'scan_again': '重新扫描',
      'rename_group': '重命名分组', 'rename_node': '重命名节点',
      'sub_added': '订阅已添加', 'node_added': '节点已添加', 'unknown_qr': '未知二维码',
      'appearance': '外观', 'theme': '主题', 'theme_dark': '深色',
      'theme_light': '浅色', 'theme_system': '跟随系统', 'language': '语言',
      'ok': '确定', 'download_log': '复制日志', 'kill_switch_on': '断网保护已开启',
      'ai_bar_prefix': '🤖  AI绕过: ',
      'profiles': '配置文件', 'profile_new': '新建配置', 'profile_name': '配置名称',
      'profile_switch': '切换配置', 'profile_delete': '删除配置', 'profile_active': '当前',
      'backup': '备份', 'backup_export': '导出备份', 'backup_import': '导入备份',
      'backup_password': '备份密码（可选）', 'backup_ok': '备份成功',
      'backup_fail': '备份失败', 'restore_ok': '恢复成功', 'restore_fail': '恢复失败',
      'restore_confirm': '当前数据将被替换，继续？',
      'backup_copied': '备份已复制到剪贴板', 'backup_password_hint': '密码（可选）',
      'split_tunnel': '分流', 'split_mode': '模式',
      'split_bypass': '绕过（所选应用跳过VPN）', 'split_proxy': '代理（仅所选应用走VPN）',
      'split_disabled': '禁用（全部流量走VPN）',
      'split_apps': '应用程序', 'split_search': '搜索应用…',
      'favourites': '收藏', 'favourite_add': '添加收藏', 'favourite_remove': '取消收藏',
      'search_nodes': '搜索节点…', 'traffic_up': '↑', 'traffic_down': '↓',
      'session_time': '会话', 'delete': '删除', 'rename': '重命名',
    },
    AuraLocale.de: {
      'app_name': 'VLY', 'connected': 'VERBUNDEN', 'connecting': 'VERBINDE…',
      'disconnected': 'GETRENNT', 'error': 'FEHLER', 'no_nodes': 'KEINE KNOTEN',
      'add_via_qr': 'Über QR-Code, Schlüssel oder Abo hinzufügen', 'scan_qr': 'QR SCANNEN',
      'nodes': 'KNOTEN', 'sort_by_ping': 'NACH PING', 'settings': 'EINSTELLUNGEN',
      'qr_scanner': 'QR-SCANNER', 'kill_switch': 'Kill Switch',
      'kill_switch_sub': 'Datenverkehr sperren wenn VPN abbricht',
      'auto_rotate': 'Auto-Rotation', 'auto_rotate_sub': 'Nach {n} Fehlern wechseln',
      'ai_bypass': 'KI Auto-Bypass', 'ai_bypass_sub': 'Automatische Umgehung ohne Updates',
      'sync_rules': 'Regeln sync.', 'sync_rules_sub': 'Regeln vom Server aktualisieren',
      'add_node': 'KNOTEN HINZUFÜGEN', 'add_key': 'SCHLÜSSEL HINZUFÜGEN',
      'add_sub': 'ABO HINZUFÜGEN', 'refresh_all': 'ALLE AKTUALISIEREN',
      'subscriptions': 'ABONNEMENTS', 'protection': 'SCHUTZ', 'logs': 'PROTOKOLLE',
      'clear': 'LÖSCHEN', 'cancel': 'Abbrechen', 'save': 'Speichern',
      'done': 'Fertig', 'scan_again': 'Erneut scannen',
      'rename_group': 'Gruppe umbenennen', 'rename_node': 'Knoten umbenennen',
      'sub_added': 'ABO HINZUGEFÜGT', 'node_added': 'KNOTEN HINZUGEFÜGT',
      'unknown_qr': 'UNBEKANNTER QR',
      'appearance': 'AUSSEHEN', 'theme': 'Design', 'theme_dark': 'Dunkel',
      'theme_light': 'Hell', 'theme_system': 'System', 'language': 'Sprache',
      'ok': 'OK', 'download_log': 'Log kopieren', 'kill_switch_on': 'Kill Switch AN',
      'ai_bar_prefix': '🤖  KI-BYPASS: ',
      'profiles': 'PROFILE', 'profile_new': 'Neues Profil', 'profile_name': 'Profilname',
      'profile_switch': 'Profil wechseln', 'profile_delete': 'Profil löschen',
      'profile_active': 'AKTIV',
      'backup': 'SICHERUNG', 'backup_export': 'Sicherung exportieren',
      'backup_import': 'Sicherung importieren', 'backup_password': 'Passwort (optional)',
      'backup_ok': 'Sicherung erstellt', 'backup_fail': 'Sicherung fehlgeschlagen',
      'restore_ok': 'Wiederhergestellt', 'restore_fail': 'Wiederherstellung fehlgeschlagen',
      'restore_confirm': 'Aktuelle Daten werden ersetzt. Fortfahren?',
      'backup_copied': 'Sicherung in Zwischenablage kopiert',
      'backup_password_hint': 'Passwort (optional)',
      'split_tunnel': 'SPLIT TUNNEL', 'split_mode': 'Modus',
      'split_bypass': 'Bypass (ausgewählte Apps umgehen VPN)',
      'split_proxy': 'Proxy (nur ausgewählte Apps über VPN)',
      'split_disabled': 'Deaktiviert (gesamter Datenverkehr über VPN)',
      'split_apps': 'Anwendungen', 'split_search': 'Apps suchen…',
      'favourites': 'FAVORITEN', 'favourite_add': 'Zu Favoriten hinzufügen',
      'favourite_remove': 'Aus Favoriten entfernen',
      'search_nodes': 'Knoten suchen…', 'traffic_up': '↑', 'traffic_down': '↓',
      'session_time': 'Sitzung', 'delete': 'Löschen', 'rename': 'Umbenennen',
    },
    AuraLocale.fr: {
      'app_name': 'VLY', 'connected': 'CONNECTÉ', 'connecting': 'CONNEXION…',
      'disconnected': 'DÉCONNECTÉ', 'error': 'ERREUR', 'no_nodes': 'AUCUN NŒUD',
      'add_via_qr': 'Ajouter via QR, clé ou abonnement', 'scan_qr': 'SCANNER QR',
      'nodes': 'NŒUDS', 'sort_by_ping': 'PAR PING', 'settings': 'PARAMÈTRES',
      'qr_scanner': 'SCANNER QR', 'kill_switch': 'Kill Switch',
      'kill_switch_sub': 'Bloquer le trafic si le VPN se déconnecte',
      'auto_rotate': 'Rotation auto', 'auto_rotate_sub': 'Changer après {n} échecs',
      'ai_bypass': 'Contournement IA', 'ai_bypass_sub': 'Contournement automatique',
      'sync_rules': 'Sync règles', 'sync_rules_sub': 'Mettre à jour depuis le serveur',
      'add_node': 'AJOUTER NŒUD', 'add_key': 'AJOUTER CLÉ',
      'add_sub': 'AJOUTER ABONNEMENT', 'refresh_all': 'TOUT ACTUALISER',
      'subscriptions': 'ABONNEMENTS', 'protection': 'PROTECTION', 'logs': 'JOURNAUX',
      'clear': 'EFFACER', 'cancel': 'Annuler', 'save': 'Enregistrer',
      'done': 'Terminé', 'scan_again': 'Scanner à nouveau',
      'rename_group': 'Renommer le groupe', 'rename_node': 'Renommer le nœud',
      'sub_added': 'ABONNEMENT AJOUTÉ', 'node_added': 'NŒUD AJOUTÉ',
      'unknown_qr': 'QR INCONNU',
      'appearance': 'APPARENCE', 'theme': 'Thème', 'theme_dark': 'Sombre',
      'theme_light': 'Clair', 'theme_system': 'Système', 'language': 'Langue',
      'ok': 'OK', 'download_log': 'Copier le journal', 'kill_switch_on': 'Kill Switch ACTIVÉ',
      'ai_bar_prefix': '🤖  BYPASS IA: ',
      'profiles': 'PROFILS', 'profile_new': 'Nouveau profil', 'profile_name': 'Nom du profil',
      'profile_switch': 'Changer de profil', 'profile_delete': 'Supprimer le profil',
      'profile_active': 'ACTIF',
      'backup': 'SAUVEGARDE', 'backup_export': 'Exporter la sauvegarde',
      'backup_import': 'Importer la sauvegarde', 'backup_password': 'Mot de passe (optionnel)',
      'backup_ok': 'Sauvegarde créée', 'backup_fail': 'Échec de la sauvegarde',
      'restore_ok': 'Restauré avec succès', 'restore_fail': 'Échec de la restauration',
      'restore_confirm': 'Les données actuelles seront remplacées. Continuer?',
      'backup_copied': 'Sauvegarde copiée dans le presse-papiers',
      'backup_password_hint': 'Mot de passe (optionnel)',
      'split_tunnel': 'TUNNEL DIVISÉ', 'split_mode': 'Mode',
      'split_bypass': 'Bypass (les apps sélectionnées contournent le VPN)',
      'split_proxy': 'Proxy (seules les apps sélectionnées via VPN)',
      'split_disabled': 'Désactivé (tout le trafic via VPN)',
      'split_apps': 'Applications', 'split_search': 'Rechercher des apps…',
      'favourites': 'FAVORIS', 'favourite_add': 'Ajouter aux favoris',
      'favourite_remove': 'Retirer des favoris',
      'search_nodes': 'Chercher des nœuds…', 'traffic_up': '↑', 'traffic_down': '↓',
      'session_time': 'Session', 'delete': 'Supprimer', 'rename': 'Renommer',
    },
    AuraLocale.es: {
      'app_name': 'VLY', 'connected': 'CONECTADO', 'connecting': 'CONECTANDO…',
      'disconnected': 'DESCONECTADO', 'error': 'ERROR', 'no_nodes': 'SIN NODOS',
      'add_via_qr': 'Agregar via QR, clave o suscripción', 'scan_qr': 'ESCANEAR QR',
      'nodes': 'NODOS', 'sort_by_ping': 'POR PING', 'settings': 'AJUSTES',
      'qr_scanner': 'ESCÁNER QR', 'kill_switch': 'Kill Switch',
      'kill_switch_sub': 'Bloquear tráfico si el VPN se desconecta',
      'auto_rotate': 'Rotación auto', 'auto_rotate_sub': 'Cambiar tras {n} fallos',
      'ai_bypass': 'IA Auto-bypass', 'ai_bypass_sub': 'Bypass automático sin actualizaciones',
      'sync_rules': 'Sync reglas', 'sync_rules_sub': 'Actualizar desde el servidor',
      'add_node': 'AGREGAR NODO', 'add_key': 'AGREGAR CLAVE',
      'add_sub': 'AGREGAR SUSCRIPCIÓN', 'refresh_all': 'ACTUALIZAR TODO',
      'subscriptions': 'SUSCRIPCIONES', 'protection': 'PROTECCIÓN', 'logs': 'REGISTROS',
      'clear': 'LIMPIAR', 'cancel': 'Cancelar', 'save': 'Guardar',
      'done': 'Hecho', 'scan_again': 'Escanear de nuevo',
      'rename_group': 'Renombrar grupo', 'rename_node': 'Renombrar nodo',
      'sub_added': 'SUSCRIPCIÓN AGREGADA', 'node_added': 'NODO AGREGADO',
      'unknown_qr': 'QR DESCONOCIDO',
      'appearance': 'APARIENCIA', 'theme': 'Tema', 'theme_dark': 'Oscuro',
      'theme_light': 'Claro', 'theme_system': 'Sistema', 'language': 'Idioma',
      'ok': 'OK', 'download_log': 'Copiar registro', 'kill_switch_on': 'Kill Switch ACTIVADO',
      'ai_bar_prefix': '🤖  BYPASS IA: ',
      'profiles': 'PERFILES', 'profile_new': 'Nuevo perfil', 'profile_name': 'Nombre del perfil',
      'profile_switch': 'Cambiar perfil', 'profile_delete': 'Eliminar perfil',
      'profile_active': 'ACTIVO',
      'backup': 'COPIA SEG.', 'backup_export': 'Exportar copia',
      'backup_import': 'Importar copia', 'backup_password': 'Contraseña (opcional)',
      'backup_ok': 'Copia creada', 'backup_fail': 'Error al crear copia',
      'restore_ok': 'Restaurado con éxito', 'restore_fail': 'Error al restaurar',
      'restore_confirm': 'Los datos actuales serán reemplazados. ¿Continuar?',
      'backup_copied': 'Copia copiada al portapapeles',
      'backup_password_hint': 'Contraseña (opcional)',
      'split_tunnel': 'TÚNEL DIVIDIDO', 'split_mode': 'Modo',
      'split_bypass': 'Bypass (apps seleccionadas evitan VPN)',
      'split_proxy': 'Proxy (solo apps seleccionadas via VPN)',
      'split_disabled': 'Desactivado (todo el tráfico via VPN)',
      'split_apps': 'Aplicaciones', 'split_search': 'Buscar apps…',
      'favourites': 'FAVORITOS', 'favourite_add': 'Agregar a favoritos',
      'favourite_remove': 'Quitar de favoritos',
      'search_nodes': 'Buscar nodos…', 'traffic_up': '↑', 'traffic_down': '↓',
      'session_time': 'Sesión', 'delete': 'Eliminar', 'rename': 'Renombrar',
    },
    AuraLocale.ar: {
      'app_name': 'VLY', 'connected': 'متصل', 'connecting': 'جارٍ الاتصال…',
      'disconnected': 'غير متصل', 'error': 'خطأ', 'no_nodes': 'لا توجد عقد',
      'add_via_qr': 'أضف عبر QR أو مفتاح أو اشتراك', 'scan_qr': 'مسح QR',
      'nodes': 'العقد', 'sort_by_ping': 'ترتيب حسب Ping', 'settings': 'الإعدادات',
      'qr_scanner': 'ماسح QR', 'kill_switch': 'مفتاح الإيقاف',
      'kill_switch_sub': 'منع حركة المرور عند انقطاع VPN',
      'auto_rotate': 'تدوير تلقائي', 'auto_rotate_sub': 'التبديل بعد {n} فشل',
      'ai_bypass': 'تجاوز AI', 'ai_bypass_sub': 'تجاوز تلقائي بدون تحديثات',
      'sync_rules': 'مزامنة القواعد', 'sync_rules_sub': 'تحديث من الخادم',
      'add_node': 'إضافة عقدة', 'add_key': 'إضافة مفتاح',
      'add_sub': 'إضافة اشتراك', 'refresh_all': 'تحديث الكل',
      'subscriptions': 'الاشتراكات', 'protection': 'الحماية', 'logs': 'السجلات',
      'clear': 'مسح', 'cancel': 'إلغاء', 'save': 'حفظ',
      'done': 'تم', 'scan_again': 'مسح مجدداً',
      'rename_group': 'إعادة تسمية المجموعة', 'rename_node': 'إعادة تسمية العقدة',
      'sub_added': 'تم إضافة الاشتراك', 'node_added': 'تم إضافة العقدة',
      'unknown_qr': 'QR غير معروف',
      'appearance': 'المظهر', 'theme': 'السمة', 'theme_dark': 'داكن',
      'theme_light': 'فاتح', 'theme_system': 'تلقائي', 'language': 'اللغة',
      'ok': 'موافق', 'download_log': 'نسخ السجل', 'kill_switch_on': 'مفتاح الإيقاف مفعّل',
      'ai_bar_prefix': '🤖  تجاوز AI: ',
      'profiles': 'الملفات الشخصية', 'profile_new': 'ملف جديد', 'profile_name': 'اسم الملف',
      'profile_switch': 'تبديل الملف', 'profile_delete': 'حذف الملف', 'profile_active': 'نشط',
      'backup': 'النسخ الاحتياطي', 'backup_export': 'تصدير النسخة',
      'backup_import': 'استيراد النسخة', 'backup_password': 'كلمة المرور (اختياري)',
      'backup_ok': 'تم إنشاء النسخة', 'backup_fail': 'فشل النسخ',
      'restore_ok': 'تم الاستعادة', 'restore_fail': 'فشل الاستعادة',
      'restore_confirm': 'سيتم استبدال البيانات الحالية. هل تريد المتابعة؟',
      'backup_copied': 'تم نسخ النسخة الاحتياطية', 'backup_password_hint': 'كلمة المرور (اختياري)',
      'split_tunnel': 'تقسيم النفق', 'split_mode': 'الوضع',
      'split_bypass': 'تجاوز (التطبيقات المحددة تتجاوز VPN)',
      'split_proxy': 'وكيل (فقط التطبيقات المحددة عبر VPN)',
      'split_disabled': 'معطل (كل حركة المرور عبر VPN)',
      'split_apps': 'التطبيقات', 'split_search': 'بحث في التطبيقات…',
      'favourites': 'المفضلة', 'favourite_add': 'إضافة إلى المفضلة',
      'favourite_remove': 'إزالة من المفضلة',
      'search_nodes': 'بحث في العقد…', 'traffic_up': '↑', 'traffic_down': '↓',
      'session_time': 'الجلسة', 'delete': 'حذف', 'rename': 'إعادة تسمية',
    },
    AuraLocale.fa: {
      'app_name': 'VLY', 'connected': 'متصل', 'connecting': 'در حال اتصال…',
      'disconnected': 'قطع شد', 'error': 'خطا', 'no_nodes': 'هیچ نودی وجود ندارد',
      'add_via_qr': 'از طریق QR، کلید یا اشتراک اضافه کنید', 'scan_qr': 'اسکن QR',
      'nodes': 'نودها', 'sort_by_ping': 'مرتب‌سازی بر اساس پینگ', 'settings': 'تنظیمات',
      'qr_scanner': 'اسکنر QR', 'kill_switch': 'Kill Switch',
      'kill_switch_sub': 'در صورت قطع VPN ترافیک را مسدود کن',
      'auto_rotate': 'چرخش خودکار', 'auto_rotate_sub': 'بعد از {n} شکست تغییر دهید',
      'ai_bypass': 'دور زدن هوش مصنوعی', 'ai_bypass_sub': 'دور زدن خودکار بدون به‌روزرسانی',
      'sync_rules': 'همگام‌سازی قوانین', 'sync_rules_sub': 'به‌روزرسانی از سرور',
      'add_node': 'افزودن نود', 'add_key': 'افزودن کلید',
      'add_sub': 'افزودن اشتراک', 'refresh_all': 'بازنشانی همه',
      'subscriptions': 'اشتراک‌ها', 'protection': 'حفاظت', 'logs': 'گزارش‌ها',
      'clear': 'پاک‌کردن', 'cancel': 'لغو', 'save': 'ذخیره',
      'done': 'تمام', 'scan_again': 'دوباره اسکن کنید',
      'rename_group': 'تغییر نام گروه', 'rename_node': 'تغییر نام نود',
      'sub_added': 'اشتراک اضافه شد', 'node_added': 'نود اضافه شد',
      'unknown_qr': 'QR ناشناخته',
      'appearance': 'ظاهر', 'theme': 'تم', 'theme_dark': 'تاریک',
      'theme_light': 'روشن', 'theme_system': 'سیستم', 'language': 'زبان',
      'ok': 'باشه', 'download_log': 'کپی گزارش', 'kill_switch_on': 'Kill Switch فعال',
      'ai_bar_prefix': '🤖  دور زدن AI: ',
      'profiles': 'پروفایل‌ها', 'profile_new': 'پروفایل جدید', 'profile_name': 'نام پروفایل',
      'profile_switch': 'تغییر پروفایل', 'profile_delete': 'حذف پروفایل', 'profile_active': 'فعال',
      'backup': 'پشتیبان', 'backup_export': 'صدور پشتیبان',
      'backup_import': 'وارد کردن پشتیبان', 'backup_password': 'رمز عبور (اختیاری)',
      'backup_ok': 'پشتیبان ایجاد شد', 'backup_fail': 'خطا در ایجاد پشتیبان',
      'restore_ok': 'بازیابی موفق', 'restore_fail': 'خطا در بازیابی',
      'restore_confirm': 'داده‌های فعلی جایگزین می‌شوند. ادامه می‌دهید؟',
      'backup_copied': 'پشتیبان در کلیپ‌بورد کپی شد', 'backup_password_hint': 'رمز عبور (اختیاری)',
      'split_tunnel': 'تونل تقسیم', 'split_mode': 'حالت',
      'split_bypass': 'بایپس (برنامه‌های انتخابی VPN را دور می‌زنند)',
      'split_proxy': 'پروکسی (فقط برنامه‌های انتخابی از VPN)',
      'split_disabled': 'غیرفعال (همه ترافیک از VPN)',
      'split_apps': 'برنامه‌ها', 'split_search': 'جستجوی برنامه‌ها…',
      'favourites': 'موردعلاقه‌ها', 'favourite_add': 'افزودن به موردعلاقه‌ها',
      'favourite_remove': 'حذف از موردعلاقه‌ها',
      'search_nodes': 'جستجوی نودها…', 'traffic_up': '↑', 'traffic_down': '↓',
      'session_time': 'جلسه', 'delete': 'حذف', 'rename': 'تغییر نام',
    },
    AuraLocale.tr: {
      'app_name': 'VLY', 'connected': 'BAĞLANDI', 'connecting': 'BAĞLANIYOR…',
      'disconnected': 'KESİLDİ', 'error': 'HATA', 'no_nodes': 'DÜĞÜM YOK',
      'add_via_qr': 'QR kodu, anahtar veya abonelik ile ekle', 'scan_qr': 'QR TARA',
      'nodes': 'DÜĞÜM', 'sort_by_ping': 'PINGE GÖRE', 'settings': 'AYARLAR',
      'qr_scanner': 'QR TARAYICI', 'kill_switch': 'Kill Switch',
      'kill_switch_sub': 'VPN kesilirse trafiği engelle',
      'auto_rotate': 'Otomatik rotasyon', 'auto_rotate_sub': '{n} başarısızlıktan sonra değiştir',
      'ai_bypass': 'AI Otomatik Atlatma', 'ai_bypass_sub': 'Güncelleme olmadan otomatik atlatma',
      'sync_rules': 'Kuralları sync.', 'sync_rules_sub': 'Sunucudan kuralları güncelle',
      'add_node': 'DÜĞÜM EKLE', 'add_key': 'ANAHTAR EKLE',
      'add_sub': 'ABONELİK EKLE', 'refresh_all': 'HEPSİNİ GÜNCELLE',
      'subscriptions': 'ABONELİKLER', 'protection': 'KORUMA', 'logs': 'GÜNLÜKLER',
      'clear': 'TEMİZLE', 'cancel': 'İptal', 'save': 'Kaydet',
      'done': 'Tamam', 'scan_again': 'Tekrar Tara',
      'rename_group': 'Grubu yeniden adlandır', 'rename_node': 'Düğümü yeniden adlandır',
      'sub_added': 'ABONELİK EKLENDİ', 'node_added': 'DÜĞÜM EKLENDİ',
      'unknown_qr': 'BİLİNMEYEN QR',
      'appearance': 'GÖRÜNÜM', 'theme': 'Tema', 'theme_dark': 'Koyu',
      'theme_light': 'Açık', 'theme_system': 'Sistem', 'language': 'Dil',
      'ok': 'Tamam', 'download_log': 'Günlüğü kopyala', 'kill_switch_on': 'Kill Switch AÇIK',
      'ai_bar_prefix': '🤖  AI BYPASS: ',
      'profiles': 'PROFİLLER', 'profile_new': 'Yeni profil', 'profile_name': 'Profil adı',
      'profile_switch': 'Profil değiştir', 'profile_delete': 'Profili sil', 'profile_active': 'AKTİF',
      'backup': 'YEDEK', 'backup_export': 'Yedeği dışa aktar',
      'backup_import': 'Yedeği içe aktar', 'backup_password': 'Şifre (isteğe bağlı)',
      'backup_ok': 'Yedek oluşturuldu', 'backup_fail': 'Yedek başarısız',
      'restore_ok': 'Geri yükleme başarılı', 'restore_fail': 'Geri yükleme başarısız',
      'restore_confirm': 'Mevcut veriler değiştirilecek. Devam edilsin mi?',
      'backup_copied': 'Yedek panoya kopyalandı', 'backup_password_hint': 'Şifre (isteğe bağlı)',
      'split_tunnel': 'BÖLÜNMÜŞ TÜNEL', 'split_mode': 'Mod',
      'split_bypass': 'Bypass (seçili uygulamalar VPN\'yi atlar)',
      'split_proxy': 'Proxy (yalnızca seçili uygulamalar VPN üzerinden)',
      'split_disabled': 'Devre dışı (tüm trafik VPN üzerinden)',
      'split_apps': 'Uygulamalar', 'split_search': 'Uygulama ara…',
      'favourites': 'FAVORİLER', 'favourite_add': 'Favorilere ekle',
      'favourite_remove': 'Favorilerden kaldır',
      'search_nodes': 'Düğüm ara…', 'traffic_up': '↑', 'traffic_down': '↓',
      'session_time': 'Oturum', 'delete': 'Sil', 'rename': 'Yeniden adlandır',
    },
    AuraLocale.pt: {
      'app_name': 'VLY', 'connected': 'CONECTADO', 'connecting': 'CONECTANDO…',
      'disconnected': 'DESCONECTADO', 'error': 'ERRO', 'no_nodes': 'SEM NÓS',
      'add_via_qr': 'Adicionar via QR, chave ou assinatura', 'scan_qr': 'ESCANEAR QR',
      'nodes': 'NÓS', 'sort_by_ping': 'POR PING', 'settings': 'CONFIGURAÇÕES',
      'qr_scanner': 'SCANNER QR', 'kill_switch': 'Kill Switch',
      'kill_switch_sub': 'Bloquear tráfego se a VPN cair',
      'auto_rotate': 'Rotação auto', 'auto_rotate_sub': 'Mudar após {n} falhas',
      'ai_bypass': 'IA Auto-bypass', 'ai_bypass_sub': 'Bypass automático sem atualizações',
      'sync_rules': 'Sync regras', 'sync_rules_sub': 'Atualizar do servidor',
      'add_node': 'ADICIONAR NÓ', 'add_key': 'ADICIONAR CHAVE',
      'add_sub': 'ADICIONAR ASSINATURA', 'refresh_all': 'ATUALIZAR TUDO',
      'subscriptions': 'ASSINATURAS', 'protection': 'PROTEÇÃO', 'logs': 'REGISTROS',
      'clear': 'LIMPAR', 'cancel': 'Cancelar', 'save': 'Salvar',
      'done': 'Feito', 'scan_again': 'Escanear novamente',
      'rename_group': 'Renomear grupo', 'rename_node': 'Renomear nó',
      'sub_added': 'ASSINATURA ADICIONADA', 'node_added': 'NÓ ADICIONADO',
      'unknown_qr': 'QR DESCONHECIDO',
      'appearance': 'APARÊNCIA', 'theme': 'Tema', 'theme_dark': 'Escuro',
      'theme_light': 'Claro', 'theme_system': 'Sistema', 'language': 'Idioma',
      'ok': 'OK', 'download_log': 'Copiar registro', 'kill_switch_on': 'Kill Switch ATIVO',
      'ai_bar_prefix': '🤖  BYPASS IA: ',
      'profiles': 'PERFIS', 'profile_new': 'Novo perfil', 'profile_name': 'Nome do perfil',
      'profile_switch': 'Trocar perfil', 'profile_delete': 'Excluir perfil', 'profile_active': 'ATIVO',
      'backup': 'BACKUP', 'backup_export': 'Exportar backup',
      'backup_import': 'Importar backup', 'backup_password': 'Senha (opcional)',
      'backup_ok': 'Backup criado', 'backup_fail': 'Falha no backup',
      'restore_ok': 'Restaurado com sucesso', 'restore_fail': 'Falha na restauração',
      'restore_confirm': 'Os dados atuais serão substituídos. Continuar?',
      'backup_copied': 'Backup copiado para a área de transferência',
      'backup_password_hint': 'Senha (opcional)',
      'split_tunnel': 'SPLIT TUNNEL', 'split_mode': 'Modo',
      'split_bypass': 'Bypass (apps selecionados ignoram VPN)',
      'split_proxy': 'Proxy (apenas apps selecionados via VPN)',
      'split_disabled': 'Desativado (todo tráfego via VPN)',
      'split_apps': 'Aplicativos', 'split_search': 'Buscar apps…',
      'favourites': 'FAVORITOS', 'favourite_add': 'Adicionar aos favoritos',
      'favourite_remove': 'Remover dos favoritos',
      'search_nodes': 'Pesquisar nós…', 'traffic_up': '↑', 'traffic_down': '↓',
      'session_time': 'Sessão', 'delete': 'Excluir', 'rename': 'Renomear',
    },
    AuraLocale.ja: {
      'app_name': 'VLY', 'connected': '接続済み', 'connecting': '接続中…',
      'disconnected': '切断', 'error': 'エラー', 'no_nodes': 'ノードなし',
      'add_via_qr': 'QR・キー・サブスクで追加', 'scan_qr': 'QRスキャン',
      'nodes': 'ノード', 'sort_by_ping': 'Pingで並べる', 'settings': '設定',
      'qr_scanner': 'QRスキャナー', 'kill_switch': 'キルスイッチ',
      'kill_switch_sub': 'VPN切断時にトラフィックをブロック',
      'auto_rotate': '自動ローテーション', 'auto_rotate_sub': '{n}回失敗後に切替',
      'ai_bypass': 'AIバイパス', 'ai_bypass_sub': '自動バイパス（更新不要）',
      'sync_rules': 'ルール同期', 'sync_rules_sub': 'サーバーから更新',
      'add_node': 'ノード追加', 'add_key': 'キー追加',
      'add_sub': 'サブスク追加', 'refresh_all': '全て更新',
      'subscriptions': 'サブスクリプション', 'protection': '保護', 'logs': 'ログ',
      'clear': 'クリア', 'cancel': 'キャンセル', 'save': '保存',
      'done': '完了', 'scan_again': '再スキャン',
      'rename_group': 'グループ名を変更', 'rename_node': 'ノード名を変更',
      'sub_added': 'サブスク追加済み', 'node_added': 'ノード追加済み',
      'unknown_qr': '不明なQR',
      'appearance': '外観', 'theme': 'テーマ', 'theme_dark': 'ダーク',
      'theme_light': 'ライト', 'theme_system': 'システム', 'language': '言語',
      'ok': 'OK', 'download_log': 'ログをコピー', 'kill_switch_on': 'キルスイッチON',
      'ai_bar_prefix': '🤖  AIバイパス: ',
      'profiles': 'プロファイル', 'profile_new': '新しいプロファイル',
      'profile_name': 'プロファイル名', 'profile_switch': 'プロファイル切替',
      'profile_delete': 'プロファイル削除', 'profile_active': 'アクティブ',
      'backup': 'バックアップ', 'backup_export': 'バックアップを書き出す',
      'backup_import': 'バックアップを読み込む', 'backup_password': 'パスワード（任意）',
      'backup_ok': 'バックアップ作成済み', 'backup_fail': 'バックアップ失敗',
      'restore_ok': '復元成功', 'restore_fail': '復元失敗',
      'restore_confirm': '現在のデータが置き換えられます。続けますか？',
      'backup_copied': 'バックアップをクリップボードにコピーしました',
      'backup_password_hint': 'パスワード（任意）',
      'split_tunnel': 'スプリットトンネル', 'split_mode': 'モード',
      'split_bypass': 'バイパス（選択したアプリはVPNをスキップ）',
      'split_proxy': 'プロキシ（選択したアプリのみVPN経由）',
      'split_disabled': '無効（すべてのトラフィックがVPN経由）',
      'split_apps': 'アプリケーション', 'split_search': 'アプリを検索…',
      'favourites': 'お気に入り', 'favourite_add': 'お気に入りに追加',
      'favourite_remove': 'お気に入りから削除',
      'search_nodes': 'ノードを検索…', 'traffic_up': '↑', 'traffic_down': '↓',
      'session_time': 'セッション', 'delete': '削除', 'rename': '名前を変更',
    },
    AuraLocale.ko: {
      'app_name': 'VLY', 'connected': '연결됨', 'connecting': '연결 중…',
      'disconnected': '연결 끊김', 'error': '오류', 'no_nodes': '노드 없음',
      'add_via_qr': 'QR코드, 키 또는 구독으로 추가', 'scan_qr': 'QR 스캔',
      'nodes': '노드', 'sort_by_ping': '핑순 정렬', 'settings': '설정',
      'qr_scanner': 'QR 스캐너', 'kill_switch': '킬 스위치',
      'kill_switch_sub': 'VPN 끊길 시 트래픽 차단',
      'auto_rotate': '자동 교체', 'auto_rotate_sub': '{n}회 실패 후 전환',
      'ai_bypass': 'AI 자동 우회', 'ai_bypass_sub': '업데이트 없이 자동 우회',
      'sync_rules': '규칙 동기화', 'sync_rules_sub': '서버에서 업데이트',
      'add_node': '노드 추가', 'add_key': '키 추가',
      'add_sub': '구독 추가', 'refresh_all': '전체 새로고침',
      'subscriptions': '구독', 'protection': '보호', 'logs': '로그',
      'clear': '지우기', 'cancel': '취소', 'save': '저장',
      'done': '완료', 'scan_again': '다시 스캔',
      'rename_group': '그룹 이름 변경', 'rename_node': '노드 이름 변경',
      'sub_added': '구독 추가됨', 'node_added': '노드 추가됨',
      'unknown_qr': '알 수 없는 QR',
      'appearance': '외관', 'theme': '테마', 'theme_dark': '다크',
      'theme_light': '라이트', 'theme_system': '시스템', 'language': '언어',
      'ok': '확인', 'download_log': '로그 복사', 'kill_switch_on': '킬 스위치 ON',
      'ai_bar_prefix': '🤖  AI 우회: ',
      'profiles': '프로필', 'profile_new': '새 프로필', 'profile_name': '프로필 이름',
      'profile_switch': '프로필 전환', 'profile_delete': '프로필 삭제', 'profile_active': '활성',
      'backup': '백업', 'backup_export': '백업 내보내기',
      'backup_import': '백업 가져오기', 'backup_password': '비밀번호 (선택)',
      'backup_ok': '백업 생성됨', 'backup_fail': '백업 실패',
      'restore_ok': '복원 성공', 'restore_fail': '복원 실패',
      'restore_confirm': '현재 데이터가 교체됩니다. 계속하시겠습니까?',
      'backup_copied': '백업이 클립보드에 복사되었습니다',
      'backup_password_hint': '비밀번호 (선택)',
      'split_tunnel': '분할 터널', 'split_mode': '모드',
      'split_bypass': '바이패스 (선택한 앱이 VPN을 우회)',
      'split_proxy': '프록시 (선택한 앱만 VPN 통과)',
      'split_disabled': '비활성 (모든 트래픽이 VPN 통과)',
      'split_apps': '앱', 'split_search': '앱 검색…',
      'favourites': '즐겨찾기', 'favourite_add': '즐겨찾기에 추가',
      'favourite_remove': '즐겨찾기에서 제거',
      'search_nodes': '노드 검색…', 'traffic_up': '↑', 'traffic_down': '↓',
      'session_time': '세션', 'delete': '삭제', 'rename': '이름 변경',
    },
    AuraLocale.uk: {
      'app_name': 'VLY', 'connected': 'ПІДКЛЮЧЕНО', 'connecting': 'ПІДКЛЮЧЕННЯ…',
      'disconnected': 'ВІДКЛЮЧЕНО', 'error': 'ПОМИЛКА', 'no_nodes': 'НЕМАЄ ВУЗЛІВ',
      'add_via_qr': 'Додати через QR, ключ або підписку', 'scan_qr': 'СКАНУВАТИ QR',
      'nodes': 'ВУЗЛІВ', 'sort_by_ping': 'ЗА ПІНГОМ', 'settings': 'НАЛАШТУВАННЯ',
      'qr_scanner': 'QR СКАНЕР', 'kill_switch': 'Kill Switch',
      'kill_switch_sub': 'Блокувати трафік при розриві VPN',
      'auto_rotate': 'Авто-ротація', 'auto_rotate_sub': 'Змінити після {n} невдач',
      'ai_bypass': 'AI Авто-обхід', 'ai_bypass_sub': 'Автоматичний обхід без оновлень',
      'sync_rules': 'Синхронізація', 'sync_rules_sub': 'Оновити правила з сервера',
      'add_node': 'ДОДАТИ ВУЗОЛ', 'add_key': 'ДОДАТИ КЛЮЧ',
      'add_sub': 'ДОДАТИ ПІДПИСКУ', 'refresh_all': 'ОНОВИТИ ВСЕ',
      'subscriptions': 'ПІДПИСКИ', 'protection': 'ЗАХИСТ', 'logs': 'ЛОГИ',
      'clear': 'ОЧИСТИТИ', 'cancel': 'Скасувати', 'save': 'Зберегти',
      'done': 'Готово', 'scan_again': 'Сканувати знову',
      'rename_group': 'Перейменувати групу', 'rename_node': 'Перейменувати вузол',
      'sub_added': 'ПІДПИСКУ ДОДАНО', 'node_added': 'ВУЗОЛ ДОДАНО',
      'unknown_qr': 'НЕВІДОМИЙ QR',
      'appearance': 'ЗОВНІШНІЙ ВИГЛЯД', 'theme': 'Тема', 'theme_dark': 'Темна',
      'theme_light': 'Світла', 'theme_system': 'Системна', 'language': 'Мова',
      'ok': 'ОК', 'download_log': 'Скопіювати лог', 'kill_switch_on': 'Kill Switch УВІМКНЕНО',
      'ai_bar_prefix': '🤖  AI ОБХІД: ',
      'profiles': 'ПРОФІЛІ', 'profile_new': 'Новий профіль', 'profile_name': 'Назва профілю',
      'profile_switch': 'Переключити', 'profile_delete': 'Видалити профіль', 'profile_active': 'АКТИВНИЙ',
      'backup': 'РЕЗЕРВНА КОПІЯ', 'backup_export': 'Створити резервну копію',
      'backup_import': 'Відновити з копії', 'backup_password': 'Пароль (необов\'язково)',
      'backup_ok': 'Копію створено', 'backup_fail': 'Помилка створення копії',
      'restore_ok': 'Відновлено успішно', 'restore_fail': 'Помилка відновлення',
      'restore_confirm': 'Поточні дані будуть замінені. Продовжити?',
      'backup_copied': 'Резервну копію скопійовано в буфер',
      'backup_password_hint': 'Пароль (необов\'язково)',
      'split_tunnel': 'РОЗДІЛЬНИЙ ТУНЕЛЬ', 'split_mode': 'Режим',
      'split_bypass': 'Байпас (обрані застосунки оминають VPN)',
      'split_proxy': 'Проксі (тільки обрані застосунки через VPN)',
      'split_disabled': 'Вимкнено (весь трафік через VPN)',
      'split_apps': 'Застосунки', 'split_search': 'Пошук застосунків…',
      'favourites': 'ОБРАНЕ', 'favourite_add': 'Додати до обраного',
      'favourite_remove': 'Видалити з обраного',
      'search_nodes': 'Пошук вузлів…', 'traffic_up': '↑', 'traffic_down': '↓',
      'session_time': 'Сесія', 'delete': 'Видалити', 'rename': 'Перейменувати',
    },
    AuraLocale.it: {
      'app_name': 'VLY', 'connected': 'CONNESSO', 'connecting': 'CONNESSIONE…',
      'disconnected': 'DISCONNESSO', 'error': 'ERRORE', 'no_nodes': 'NESSUN NODO',
      'add_via_qr': 'Aggiungi tramite QR, chiave o abbonamento', 'scan_qr': 'SCANSIONA QR',
      'nodes': 'NODI', 'sort_by_ping': 'PER PING', 'settings': 'IMPOSTAZIONI',
      'qr_scanner': 'SCANNER QR', 'kill_switch': 'Kill Switch',
      'kill_switch_sub': 'Blocca il traffico se la VPN cade',
      'auto_rotate': 'Rotazione auto', 'auto_rotate_sub': 'Cambia dopo {n} fallimenti',
      'ai_bypass': 'AI Auto-bypass', 'ai_bypass_sub': 'Bypass automatico senza aggiornamenti',
      'sync_rules': 'Sync regole', 'sync_rules_sub': 'Aggiorna dal server',
      'add_node': 'AGGIUNGI NODO', 'add_key': 'AGGIUNGI CHIAVE',
      'add_sub': 'AGGIUNGI ABBONAMENTO', 'refresh_all': 'AGGIORNA TUTTO',
      'subscriptions': 'ABBONAMENTI', 'protection': 'PROTEZIONE', 'logs': 'REGISTRI',
      'clear': 'CANCELLA', 'cancel': 'Annulla', 'save': 'Salva',
      'done': 'Fatto', 'scan_again': 'Scansiona di nuovo',
      'rename_group': 'Rinomina gruppo', 'rename_node': 'Rinomina nodo',
      'sub_added': 'ABBONAMENTO AGGIUNTO', 'node_added': 'NODO AGGIUNTO',
      'unknown_qr': 'QR SCONOSCIUTO',
      'appearance': 'ASPETTO', 'theme': 'Tema', 'theme_dark': 'Scuro',
      'theme_light': 'Chiaro', 'theme_system': 'Sistema', 'language': 'Lingua',
      'ok': 'OK', 'download_log': 'Copia registro', 'kill_switch_on': 'Kill Switch ATTIVO',
      'ai_bar_prefix': '🤖  BYPASS IA: ',
      'profiles': 'PROFILI', 'profile_new': 'Nuovo profilo', 'profile_name': 'Nome profilo',
      'profile_switch': 'Cambia profilo', 'profile_delete': 'Elimina profilo', 'profile_active': 'ATTIVO',
      'backup': 'BACKUP', 'backup_export': 'Esporta backup',
      'backup_import': 'Importa backup', 'backup_password': 'Password (opzionale)',
      'backup_ok': 'Backup creato', 'backup_fail': 'Backup fallito',
      'restore_ok': 'Ripristinato con successo', 'restore_fail': 'Ripristino fallito',
      'restore_confirm': 'I dati attuali verranno sostituiti. Continuare?',
      'backup_copied': 'Backup copiato negli appunti', 'backup_password_hint': 'Password (opzionale)',
      'split_tunnel': 'SPLIT TUNNEL', 'split_mode': 'Modalità',
      'split_bypass': 'Bypass (le app selezionate bypassano la VPN)',
      'split_proxy': 'Proxy (solo le app selezionate tramite VPN)',
      'split_disabled': 'Disabilitato (tutto il traffico tramite VPN)',
      'split_apps': 'Applicazioni', 'split_search': 'Cerca app…',
      'favourites': 'PREFERITI', 'favourite_add': 'Aggiungi ai preferiti',
      'favourite_remove': 'Rimuovi dai preferiti',
      'search_nodes': 'Cerca nodi…', 'traffic_up': '↑', 'traffic_down': '↓',
      'session_time': 'Sessione', 'delete': 'Elimina', 'rename': 'Rinomina',
    },
  };

  static const Map<AuraLocale, String> localeNames = {
    AuraLocale.en: 'English', AuraLocale.ru: 'Русский', AuraLocale.zh: '中文',
    AuraLocale.de: 'Deutsch', AuraLocale.fr: 'Français', AuraLocale.es: 'Español',
    AuraLocale.ar: 'العربية', AuraLocale.fa: 'فارسی', AuraLocale.tr: 'Türkçe',
    AuraLocale.pt: 'Português', AuraLocale.ja: '日本語', AuraLocale.ko: '한국어',
    AuraLocale.uk: 'Українська', AuraLocale.it: 'Italiano',
  };
}